### ISSUE TITLE
mkdir fails

### ISSUE THREAD

**Issue by bugi** [jplana/python-etcd#107]
Under [set a key](http://python-etcd.readthedocs.org/en/latest/#set-a-key) in the docs it's mentioned that you can perform a mkdir operation:
```
# mkdir
client.write('/nodes/queue', dir=True)
```

That fails for me with
```
TypeError: write() takes at least 3 non-keyword arguments (2 given)
```

**Comment by durzo** [comment]
have you tried passing value=None or value=False ?

**Comment by bugi** [comment]
Both value=None and value=False worked.

Is the appropriate fix in the docs or in the code?  For docs I could submit a pull request, but that seems like documenting a workaround.  For code, that would necessarily change the interface of the write() method.
