### ISSUE TITLE
client.watch doesn't work as expected.

### ISSUE THREAD

**Issue by ppanagiotis** [jplana/python-etcd#109]
I am trying the following as described  [here](http://python-etcd.readthedocs.org/en/latest/#get-a-key) :
```python
r = client.watch('/test_folder')
```
and then
``` python
client.set('/test_folder/test', 'abc')
```
Althought the value is set correctly the watch command never returned.

I tried to use 
```python
client.read('/test_folder', wait=True)
 ```

 but I got the same results. :-(

Any suggestions?
Thank you.

**Comment by lavagetto** [comment]
Hi, did you try with the latest version of the code? I could not reproduce your problem.

**Comment by lavagetto** [comment]
Sorry, just got what is wrong:

client.read('/test_folder', wait=True, recursive=True)

should do the trick for you.
