### ISSUE TITLE
Connection pooling doesn't work for 127.0.0.1 connections

### ISSUE THREAD

**Issue by mwitkow-io** [jplana/python-etcd#110]
There's a bug in `python-gcloud` in how it handles `HTTPConnectionPool`.

The constructor of `Client` calls 
```python
    self.http = urllib3.PoolManager(num_pools=10, **kw)
```

The `PoolManager` is what managed per-host connection pools (usually `HTTPConnectionPool` or `HTTPSConnectionPool`). These by default have `maxsize=1`, meaning that it will only keep one connection per host. If multiple connections are sent to the same `Client`, this leads to `No JSON decoded`, because the connection will be rejected.

`Client` should allow for pooling for localhost connections.

**Comment by lavagetto** [comment]
Hi, looking at the urllib3 documentation I see:

 |  :param maxsize:
 |      Number of connections to save that can be reused. More than 1 is useful
 |      in multithreaded situations. If ``block`` is set to false, more
 |      connections will be created but they will not be saved once they've
 |      been used.
 |  
 |  :param block:
 |      If set to True, no more than ``maxsize`` connections will be used at
 |      a time. When no free connections are available, the call will block
 |      until a connection has been released. This is a useful side effect for
 |      particular multithreaded situations where one does not want to use more
 |      than maxsize connections per host to prevent flooding.

Also, looking at the code confirms that what you think is quite wrong - more than one connection will be possible, they just won't be reused.

So, while I agree your patch is surely going to provide a performance benefit, I'm not sure this is the reason for the "No json decoded" error. If this empirically fixes it, then good to know :)
