### ISSUE TITLE
Cannot use the "watch" with decode server response error

### ISSUE THREAD

**Issue by mr-kelly** [jplana/python-etcd#116]
![image](https://cloud.githubusercontent.com/assets/520852/8844117/f784a122-3143-11e5-8677-332c20955d6b.png)

etcd 2.0.13 windows-amd64
python-etcd 0.3.3
python 2.7

**Comment by mr-kelly** [comment]
![image](https://cloud.githubusercontent.com/assets/520852/8844343/b237f8b4-3146-11e5-9fcf-8c334166a6ba.png)
Catch the etcd errorCode 209

**Comment by mr-kelly** [comment]
I found the problem:

When I turn on the gevent's monkey.patch_all().............

this problem will happen

**Comment by lavagetto** [comment]
Can I see your code please?

Gevent support should be there but never tested properly. and surely not on windows.

**Comment by mr-kelly** [comment]
![image](https://cloud.githubusercontent.com/assets/520852/8847581/abc345d0-3162-11e5-81a3-c1fcae7f77d8.png)
![image](https://cloud.githubusercontent.com/assets/520852/8847585/b1c1725e-3162-11e5-9735-aed4326cb00d.png)

Just some test code, with monkey patch all

**Comment by lavagetto** [comment]
@mr-kelly I can't reproduce your problem with some sample code, also I suspect that if you tried the latest git version of python-etcd that would solve some of your problems.

Also, I don't have access to any windows machine so I can't verify the problem is windows-specific or not.

My test code:
```
import gevent
from gevent import monkey
monkey.patch_all()
import etcd

cl = etcd.Client()


def w(what):
    print 'now watch'
    rval = cl.read(what, wait=True)
    print rval


t1=gevent.spawn(w, '/abs')
t2=gevent.spawn(w, '/abc')
gevent.joinall([t1,t2])
```
