### ISSUE TITLE
urllib3 isn't found like I'd expect

### ISSUE THREAD

**Issue by dannysauer** [jplana/python-etcd#119]
Is this something that changed between Python 2.6 and 2.7, or something with a newer version of requests (which I just built from the latest github tag as well)?

    Python 2.6.6 (r266:84292, Nov 21 2013, 10:50:32)
    [GCC 4.4.7 20120313 (Red Hat 4.4.7-4)] on linux2
    Type "help", "copyright", "credits" or "license" for more information.
    >>> import etcd
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
      File "/usr/lib/python2.6/site-packages/etcd/__init__.py", line 2, in <module>
        from .client import Client
      File "/usr/lib/python2.6/site-packages/etcd/client.py", line 17, in <module>
        import urllib3
    ImportError: No module named urllib3
    >>> import requests.packages.urllib3
    >>> requests.packages.urllib3
    <module 'requests.packages.urllib3' from 'requests/packages/urllib3/__init__.pyc'>

**Comment by lavagetto** [comment]
did you try to install urllib3 too under python 2.6?

Also, we only officially support python 2.7, so no idea about what happens with 2.6

**Comment by dannysauer** [comment]
That's why I asked. The urllib3 module imports just fine when imported as "requests.packages.urllib3" but the etcd module does not find it. I don't know a lot about Python historically, so I don't know if this is an "old Python" thing, a urllib3 thing, a search path thing, or a compatability issue with  how this module is written. The Internet is useless since I don't know exactly what's wrong, so I was hoping for a clue here. :)

**Comment by lavagetto** [comment]
how did you install python-etcd?

**Comment by dannysauer** [comment]
Pulled the "0.4.1" tag from git, ran "python setup.py bdist_rpm ...", signed the RPM, and then "yum localinstall"
