### ISSUE TITLE
etcdserver: failed to purge snap file

### ISSUE THREAD

**Issue by rfyiamcool** [jplana/python-etcd#128]
I use etcd v2.0.5 for Windows 64 bits (Windows 7 and 8.1), and after some hours, etcd crashes with this error message:

 etcdserver: failed to purge wal file remove etcd-data/member/wal/0000000000000002-0000000000004e23.wal: The process cannot access the file because it is being used by another process.
If I try to restart etcd, I get the same error.
I checked: this file is not used by any process, I could remove it manually and etcd could restart normally.

**Comment by lavagetto** [comment]
This issue should be reported to coreos/etcd, not to a client library
