### ISSUE TITLE
Support for creating directories

### ISSUE THREAD

**Issue by vaidik** [jplana/python-etcd#13]
`etcd` API provides support for creating directories. Support for that seems missing in the current implementation of this library.

Or am I missing something? I haven't looked at the code in depth.

**Comment by Gourds** [comment]
@jplana In addition to the following method, Is there have any more direct way?
```
client.set('/nodes/directory/key', 1)
```

**Comment by saurabhsinghmaurya** [comment]
Same question here
how to create empty directory?
