### ISSUE TITLE
If I use this method to monitor, I will not lose data ?

### ISSUE THREAD

**Issue by rfyiamcool** [jplana/python-etcd#130]
for event in client.eternal_watch('/nodes',recursive = True):
    print event.action

If I use this method to monitor, I will not lose data ?

Of course, I tested the next, no loss of data .However, I still want to find you to confirm this .

Thanks U !

**Comment by lavagetto** [comment]
@rfyiamcool in theory, no, you're not going to lose data; however I would not rely on it as a replication method.
