### ISSUE TITLE
Log spam when reads (expectedly) time out

### ISSUE THREAD

**Issue by fasaxc** [jplana/python-etcd#132]
If a read times out, we generate this error-level log:
```
2015-10-07 08:57:24,034 [ERROR][51716/5] etcd.client 783: Request to server http://localhost:4001 failed: ReadTimeoutError("HTTPConnectionPool(host='localhost', port=4001): Read timed out.",)
```
When doing a watch, such read timeouts are expected so it's not really an error.  That makes the log a lot less useful when there really is an error.

I'd like to fix that by passing a flag to api_execute that tells it whether a ReadTimeout is expected (or by checking for wait=True int eh arguments) and suppressing the error.  WDYT?

**Comment by lavagetto** [comment]
I think this is a very good idea - I would just check for wait=True and
make it DTRT.

Thanks!

**Comment by fasaxc** [comment]
Will do (sorry, missed the notification from Github.)
