### ISSUE TITLE
Can you please make a new release?

### ISSUE THREAD

**Issue by nbartos** [jplana/python-etcd#133]
I'm working on Project Calico, and I would really like to be able to have everyone use a released version of python-etcd, instead of a Calico-specific or nonreleased version.  Now that the required patches have landed in master, would it be too much to ask to get a new release up on pypi?

**Comment by jplana** [comment]
Sure. Will do overnight.

**Comment by nbartos** [comment]
Thanks!

**Comment by jplana** [comment]
Released as 0.4.2
