### ISSUE TITLE
Please push to PyPI

### ISSUE THREAD

**Issue by smurfix** [jplana/python-etcd#149]
You seem to have forgotten to push 0.4.3 to PyPI.

**Comment by lavagetto** [comment]
@jplana ping :)

**Comment by lavagetto** [comment]
btw, just found an issue and fixed it. It might be a good idea to push directly 0.4.4 to pypi too, or to move the tag here.

**Comment by jplana** [comment]
@smurfix  I'm really sorry for the long delay. I just uploaded to PyPi the 0.4.3 version including the latest fix by @lavagetto ( d29eabf0d798aadfcf7cb881d3f9ad403c99542b ). I moved the tag, not very fan of this, but as it was still "unreleased"...
