### ISSUE TITLE
Code to catch ReadTimeoutError misses MaxRetryError

### ISSUE THREAD

**Issue by fasaxc** [jplana/python-etcd#160]
We have code to catch ReadTimeoutError and wrap as EtcdWatchTimeout:

```
                    if (isinstance(params, dict) and
                        params.get("wait") == "true" and
                        isinstance(e,
                                   urllib3.exceptions.ReadTimeoutError)):
                        _log.debug("Watch timed out.")
                        raise etcd.EtcdWatchTimedOut(
                            "Watch timed out: %r" % e,
                            cause=e
                        )
```

But, at least with urllib3 1.10.2 on RedHat, urllib3 can raise MaxRetryError (with a cause of ReadTimeoutError) on this code path instead.  We should catch that too.

I'm not sure why we get MaxRetryError; the issue could be that we're misconfiguring urllib3 so that it retries on a watch, which we probably don't want.  Or it may just be a difference between urllib3 versions.  The except block was added against 1.7.1-1ubuntu4, which is the version that ships with Ubuntu 14.04, IIRC.

**Comment by lavagetto** [comment]
I cannot reproduce this with urllib3 1.19.1 which I'm using atm.
