### ISSUE TITLE
Whats the correct way to add cert file from composeio?

### ISSUE THREAD

**Issue by sirvon** [jplana/python-etcd#165]
This isn't working....

```python
client = etcd.Client(
         host=os.environ.get("ETCD_HOST"),
         port=int(os.environ.get("ETCD_PORT")),
         allow_reconnect=True,
         cert=('./etcdcert',"etcdcert"),
         protocol='https',
         username=os.environ.get("ETCD_USERNAME"),
         password=os.environ.get("ETCD_PASSWORD"))
```

**Comment by lavagetto** [comment]
I don't use composeio and I don't intend learning much about how they work either; but python-etcd has been proven to work with SSL certificates perfectly fine (we also have some integration testing for that).

Sorry but this seems more as a question for some support forum than an issue of the code/documentation.
