### ISSUE TITLE
[Feature Request] Make it easily possible to iterate over the direct children of a node.

### ISSUE THREAD

**Issue by JostBaron** [jplana/python-etcd#166]
This is currently not possible, it's only possible to iterate over the complete subtree of a node.

To get only the children of that node, one would need to either access the private `_children` member of the result, or filter the complete subtree using `get_subtree()`, which is inefficient.

**Comment by cizixs** [comment]
I am using `python-etcd==0.4.3`, the following code will return the direct children of a node:

    res = client.get("/some/dir")
    list(res.leaves)

If `recursive=True` is passed as  a parameter, it will return all `key nodes`(the real leave node).

**Comment by lavagetto** [comment]
What @cizixs said :)

**Comment by JostBaron** [comment]
Actually, when reading the code (and also when interpreting the setting name correctly), it seems that not the children of a node are returned, but all the leave-nodes below the node.

But what I want is the list of direct children of a node (even for `recursive=true`) - I need this to parse the retrieved config into an internal data structure.
