### ISSUE TITLE
Using a Lock as a context manager leads to AttributeError

### ISSUE THREAD

**Issue by Konfuzzyus** [jplana/python-etcd#170]
According to the documentation at http://python-etcd.readthedocs.io/en/latest/, the following code should be valid usage of the Lock class:

```
client = etcd.Client()
with etcd.Lock(client, 'customer1') as my_lock:
    do_stuff()
    my_lock.is_acquired()  # True
    my_lock.acquire(lock_ttl = 60)
my_lock.is_acquired() # False
```

This throws an AttributeError at my_lock.is_acquired(), because my_lock is None at that point.    

The reason is the implementation of **enter** and **exit** on Lock, which do not comply with the context manager contract, see https://docs.python.org/2/reference/datamodel.html#context-managers.

e.g.

```
def __enter__(self):
        """
        You can use the lock as a contextmanager
        """
        self.acquire(blocking=True, lock_ttl=0)
        # missing return self

    def __exit__(self, type, value, traceback):
        self.release()
        # missing return False
```

**Comment by eyurtsev** [comment]
+1

**Comment by Oloremo** [comment]
Is it a time to fork?

**Comment by lavagetto** [comment]
This is now solved with the latest additions.
