### ISSUE TITLE
how can i check whether a key exists

### ISSUE THREAD

**Issue by zgfh** [jplana/python-etcd#173]
i think this is not right

```
try:
    client.read('/invalid/path')
except etcd.EtcdKeyNotFound:
    # do something
    print "error"
```

i think  method isExists() will be better

**Comment by zgfh** [comment]
i think this is not right
```
try:
    client.read('/invalid/path')
except etcd.EtcdKeyNotFound:
    # do something
    print "error"
```
i think  method isExists() will be better

**Comment by cueBall123** [comment]
@lavagetto Is there a reason this request is invalid?? It is on the user to validate the existence of the key by querying the endpoint directly?

**Comment by cueBall123** [comment]
https://github.com/coreos/etcd/pull/4194/commits/f67f6d7c7c9c5d03b5605672302d46885587ad19
