### ISSUE TITLE
any plan to support v3 api?

### ISSUE THREAD

**Issue by yy2008** [jplana/python-etcd#177]
Is there any plan to support v3?

**Comment by lavagetto** [comment]
@yy2008 I don't honestly see myself having the time in the near future to work on the v3 api, as from what I get we'll need to create a whole new library, more or less.

Sorry, but I am not getting paid to develop python-etcd, and thus it's just a weekends enterprise.

I fully intend to work on it though, because I see the clear advantages.

If anyone has suggestions on how to support the v3 api minimizing the harm done to users, I'm all ears :)

**Comment by durzo** [comment]
+1 for v3 support, now that v3 is officially launched and looks amazing.

perhaps the v3 client should be a separate project so that it does not interfere with this v2 project - python-etcd3 ?

**Comment by lavagetto** [comment]
@durzo in fact I am planning to start working on a v3 client this week if no one else picks up the chore, but it's going to be a separate project.

**Comment by durzo** [comment]
@lavagetto let me know if I can help in any way (coding or testing). I have yet to actually read the v3 client api docs, but it cant be much harder than the v2 implementation... right? :smile:

**Comment by lavagetto** [comment]
@durzo in many ways it's easier, as all the low-level dirt is hidden under the grpc (see https://grpc.io) carpet; in some ways, I have to figure out again from scratch all the implementation details from docs that are at best incomplete.

I have some code that can actively read/write on an insecure channel to etcd, but it's clearly not nearly enough :) As soon as I have a working stub of a real library, I'll publish it and contributions will be welcome!

**Comment by durzo** [comment]
@lavagetto any update to this? can you post any working code for us to start contributing to?

**Comment by durzo** [comment]
Seems someone has made progress on this, see https://github.com/kragniz/python-etcd3

**Comment by lavagetto** [comment]
@durzo yeah but well, I see they haven't resolved the two big issues I had with the etcd3 client, namely watching and auth are unsupported. If you think it's worth it, I can just release the code I wrote as-is in 2-3 days, but any etcd client that doesn't support watching is pretty useless IMHO.

**Comment by lavagetto** [comment]
FTR, I've started contributing to python-etcd3 and I plan to add a compatibility layer here. For details refer to #232
