### ISSUE TITLE
please update 2.6 support bug fix to pypi

### ISSUE THREAD

**Issue by bagel** [jplana/python-etcd#193]
Collecting python-etcd
  Using cached python-etcd-0.4.3.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-9NRDkU/python-etcd/setup.py", line 12, in <module>
        if sys.version_info.major == 2:
    AttributeError: 'tuple' object has no attribute 'major'

```
----------------------------------------
```

Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-9NRDkU/python-etcd/

I saw this bug had been fixed, but pypi not update, please update. thanks!

**Comment by nichenke** [comment]
We could really use a new release to pick up other changes - refresh(), etc.

**Comment by adeck** [comment]
+1 for pushing [0.4.3](https://github.com/jplana/python-etcd/releases/tag/0.4.3) to `pip`.

**Comment by lavagetto** [comment]
Already done :)
