### ISSUE TITLE
how to watch 1000 keys?

### ISSUE THREAD

**Issue by humingcheng** [jplana/python-etcd#199]
There is an application need to do this work. I can register 1000 watchers with a zookeeperClient to realize that function，but how can I do that with a python-etcd-client?
It is a good idea to watch the root key and use "recursive=true", but sometimes the application must watch  every key independently.
How should I do?

**Comment by durzo** [comment]
we watch the root with recursive=true and then iterate over each change and perform different actions based on the 2nd level key. with this method we are able to watch over 70,000 keys with ms response times.

**Comment by humingcheng** [comment]
@durzo Thank you very much! But I still don't now how to watch 5 keys? It must be wasteful to watch the root key for 5 target keys.

**Comment by lavagetto** [comment]
@humingcheng this is a problem we can't really resolve as etcd responds to single commands only in version 2;

What you could do is to wrap python-etcd into a async loop like gevent and add greenlets that watch the individual keys.
