### ISSUE TITLE
python-etcd equivalent for `etcdctl --no-sync`

### ISSUE THREAD

**Issue by timfeirg** [jplana/python-etcd#207]
I'm doing this thing where I have to connect to a remote etcd proxy from my local machine, but I can't connect to the real etcd cluster nodes, so I have to use 

```shell
$ etcdctl --no-sync --endpoints http://**.**.**.**:2379 ls "/eru-core"
```

to issue any `etcdctl` commands, otherwise I get:

```shell
$ etcdctl --endpoints http://10.x.x.17:2379 ls "/eru-core"
Error:  client: etcd cluster is unavailable or misconfigured
error #0: client: endpoint http://10.x.x.11:2379 exceeded header timeout
error #1: client: endpoint http://10.x.x.12:2379 exceeded header timeout
error #2: client: endpoint http://10.x.x.13:2379 exceeded header timeout
```

But with `python-etcd`, I can't seem to find this `--no-sync` mode, and so I can't use `python-etcd` in my local develop environment.

**Comment by lavagetto** [comment]
I'm not sure what your problem is, but what you want is achieved if you set allow_reconnect to False when initializing the client.
