### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by Oloremo** [jplana/python-etcd#208]
Some features from the master, like lock_prefix customisation is really nice to have.

**Comment by ashcrow** [comment]
:+1: on doing a new release, but I think #210 should be addressed as well.

**Comment by frenzymadness** [comment]
Hello.

A new release would be very appreciated because in the latest release there is still a dependency on nonexisting `dnspython3` which makes us some troubles with packaging this software for Fedora.

Have a nice day.

**Comment by jplana** [comment]
@frenzymadness  I'll review the changes and get a new release tonight.

**Comment by lavagetto** [comment]
@jplana I would like to take the time to review a couple of outstanding PRs before we make a release.

**Comment by jplana** [comment]
@lavagetto sure, I just wanted to review this specific change along with another one (#225) and release, but let me know when you're done.

**Comment by Oloremo** [comment]
@jplana any chances for #170 fix? Current readme suggest to use with statement which is not working

**Comment by lavagetto** [comment]
FTR, I am reviewing all PRs right now; once I am done, I think we can make a release.

**Comment by lavagetto** [comment]
@jplana I've pretty much concluded all the work on this version of python-etcd. I think a release should be prepared. Then we can move on to do a new major release where we can do some breaking changes people are asking for, and maybe add etcd3 support

**Comment by jplana** [comment]
@lavagetto Ok! I'll get it tagged & uploaded tonight.

**Comment by frenzymadness** [comment]
@jplana Cool, thank you a lot. I am looking forward new release.

**Comment by wonderfry** [comment]
I really wonder that  if the owner's locker expired during executing some stuff, how our lock mechanism to address. It seems that our mechanism ignore it

**Comment by wonderfry** [comment]
@jplana  I really wonder that if the owner's locker expired during executing some stuff, how our lock mechanism to address. It seems that our mechanism ignore it

**Comment by wonderfry** [comment]
@jplana why does the mechanism have no util similar to  TimerTask  when the lock is nearly to expired?

**Comment by ainlolcat** [comment]
Can we expect python-etcd 0.4.5 anytime soon?

**Comment by jplana** [comment]
Release 0.4.5 uploaded. Sorry about the delay...
