### ISSUE TITLE
Do we have any plans to add members APIs?

### ISSUE THREAD

**Issue by pankit** [jplana/python-etcd#235]
I was interested in adding the members to a running cluster using using the library. Do, we have any plans to do so? https://coreos.com/etcd/docs/latest/v2/members_api.html#add-a-member

**Comment by socketpair** [comment]
https://github.com/jplana/python-etcd/pull/219

**Comment by lavagetto** [comment]
I am not working on this as I honestly think etcdctl is enough for such actions, but if the current PR gets amended, I'm happy to merge it.

**Comment by lavagetto** [comment]
Duplicate of #218
