### ISSUE TITLE
Use SSL without verifying certificates

### ISSUE THREAD

**Issue by cizixs** [jplana/python-etcd#240]
I have a self-signed SSL etcd cluster running, and passing around `ca.crt` file is tiresome and prune to errors. 

I trust my own etcd server, so I wonder is there a way to skip SSL verification which using `python-etcd`?

**Comment by lavagetto** [comment]
I'm sorry but allowing to skip SSL verification of cert validity is against the whole idea of how encryption works.

I personally will never, ever, add the ability to skip a check to my own library (while you have your means to do it anyways, if you really want to shoot yourself in the foot, given we use urllib3).
