### ISSUE TITLE
Will break with etcd 3.2

### ISSUE THREAD

**Issue by maikzumstrull** [jplana/python-etcd#244]
I just tried etcd 3.2rc1, and while it still has the v2 API as a fallback, the /v2/machines call [has been removed](https://github.com/coreos/etcd/commit/2bb33181b6c8fbe8109fc668a19ce4ab46c605ec). It's used in this library if reconnects are enabled.

**Comment by maikzumstrull** [comment]
etcd has decided to revert: https://github.com/coreos/etcd/pull/8062

**Comment by lavagetto** [comment]
In any case, I plan to add proper support for etcd 3.x with an Api as
similar ad possible to the current one, using python-etcd3 as a base.

To that end, I'm contributing to the upstream project in the meanwhile to
add features we are used to with the current library. The goal is to make
it relatively easy to port your software to etcd3 without a complete
rewrite.

G.

Il ven 9 giu 2017, 20:39 Maik Zumstrull <notifications@github.com> ha
scritto:

**Comment by lavagetto** [comment]
Please refer to #232 for updates.
