### ISSUE TITLE
Still maintained?

### ISSUE THREAD

**Issue by tuxflo** [jplana/python-etcd#284]
Since this project is listed on the official ["Libraries and Tools"](https://etcd.io/docs/v3.5/integrations/#python) page, I wonder if it is still maintained.
Because otherwise I'd remove it from the Libraries page to keep it clean.

**Comment by lavagetto** [comment]
It's still maintained, somewhat, meaning I'll keep the code working with modern python, but I'm not going to make big changes to the codebase anymore.
