### ISSUE TITLE
Prepare for a new release

### ISSUE THREAD

**Issue by lavagetto** [jplana/python-etcd#41]
We need to do the following:

- Support calls to /stats (not sure it's fundamental, though)
- Review docs
- Model integration tests on the structure of the documented etcd API as much as possible

Then I'd say we're ready for a new release, as a ton of bugs have been resolved.

**Comment by durzo** [comment]
I just installed the latest (0.3.2) through pip to discover it is seriously behind (no recursive watcher support).. is 0.4.0 due any time soon?

**Comment by lavagetto** [comment]
We had 0.3.3 out and I guess we're going to have 0.4.0 out soon-ish (as I am fixing a few issues right now).
