### ISSUE TITLE
Connection fails when the first host in the list is down

### ISSUE THREAD

**Issue by l3af** [jplana/python-etcd#51]
If you send a tuple list to host parameter, if the first host fails the urllib3.exceptions.TimeoutError is not caught and the code fails.
Should be added around line 527 in client.py

**Comment by lavagetto** [comment]
So... if you have an incorrect configuration you get an exception. Not that strange, but I'll try to handle that gracefully - it's not easy, as a TimeoutError can happen also because you reached the urllib request timeout.

**Comment by lavagetto** [comment]
Also, trying to reproduce your bug, I get a different (as expected) error - urllib3.exceptions.MaxRetryError just when I try to instantiate etcd.Client
```
>>> host_list = ( ('127.0.0.1', 4000), ('127.0.0.1', 4001) )
>>> c = etcd.Client(host=host_list, read_timeout=5, allow_reconnect=True, allow_redirect=True)
[CUT]
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='127.0.0.1', port=4000): Max retries exceeded with url: /v2/machines (Caused by ProtocolError('Connection aborted.', error(111, 'Connection refused')))
```

Which is a perfectly fine way to fail in my opinion, but I can handle that gracefully I guess.

Still, this is not the problem you reported, so...
