### ISSUE TITLE
Project active?

### ISSUE THREAD

**Issue by durzo** [jplana/python-etcd#82]
We use this library in our company and I noticed this project hasn't had any updates in some time.. can anyone shed some light on if it is still actively maintained and will receive updates to ensure it continues working with future versions of etcd?

If not, can anyone suggest another python library?

**Comment by lavagetto** [comment]
hey, it is active, personally I just didn't have time to work on it a lot
lately.

Since I will probably get back to using etcd extensively at work, I'll be
able to dedicate some time to it.

As far as uploading to pip, we should wait for @jplana to chime in

**Comment by durzo** [comment]
@jplana - getting pip updated would be great

**Comment by jplana** [comment]
Sorry for the late answer. My time for open source projects has been quite limited for the past year, I hope to recover some of it.

I've just published 0.3.3 to pypi, but please let me know If I need to prioritize any of the still open issues/PR.
