### ISSUE TITLE
python etcd.EtcdException: Unable to decode server response

### ISSUE THREAD

**Issue by dreameryan** [jplana/python-etcd#83]
With etcd-v2.0.9-linux-amd64.
I run these 2 etcd process on two machine:
/home/idcuser/HATest/etcd-v2.0.9-linux-amd64/etcd -name monitorserver1 -listen-peer-urls http://10.120.73.86:7001 -listen-client-urls http://10.120.73.86:4001 -initial-cluster-token monitorserver-cluster -initial-advertise-peer-urls http://10.120.73.86:7001 -initial-cluster monitorserver1=http://10.120.73.86:7001,monitorserve2=http://10.112.206.10:2380 -initial-cluster-state new &>> /home/idcuser/HATest/etcd.log &

/home/idcuser/HATest/etcd-v2.0.9-linux-amd64/etcd -name monitorserver2 -listen-peer-urls http://10.112.206.10:2380 -listen-client-urls http://10.112.206.10:2379 -initial-cluster-token monitorserver-cluster -initial-advertise-peer-urls http://10.112.206.10:2380 -initial-cluster monitorserver1=http://10.120.73.86:7001,monitorserver2=http://10.112.206.10:2380 -initial-cluster-state new &>> /home/idcuser/HATest/etcd.log &

Then in one machine 10.120.73.86:
I run following command through python:
etcd= etcd.Client(host='10.120.73.86', port=4001)
leader = etcd.read('/ms/leader/name' ).value
etcd.write( '/ms/leader/name', serverName, ttl=TTL )

Exception throws when I calling etcd.write( '/ms/leader/name', serverName, ttl=TTL )
Traceback (most recent call last):
File "/home/idcuser/HATest/HA_monitor2.python", line 118, in
main()
File "/home/idcuser/HATest/HA_monitor2.python", line 110, in main
run()
File "/home/idcuser/HATest/HA_monitor2.python", line 34, in run
leaderSelect()
File "/home/idcuser/HATest/HA_monitor2.python", line 50, in leaderSelect
beLeader()
File "/home/idcuser/HATest/HA_monitor2.python", line 66, in beLeader
etcd.write( '/ms/leader/name', serverName, ttl=TTL ) # value=xxxx
File "/usr/lib/python2.7/site-packages/python_etcd-0.3.2-py2.7.egg/etcd/client.py", line 272, in write
response = self.api_execute(path, method, params=params)
File "/usr/lib/python2.7/site-packages/python_etcd-0.3.2-py2.7.egg/etcd/client.py", line 587, in api_execute
return self.handle_server_response(response)
File "/usr/lib/python2.7/site-packages/python_etcd-0.3.2-py2.7.egg/etcd/client.py", line 603, in handle_server_response
etcd.EtcdError.handle(**r)
File "/usr/lib/python2.7/site-packages/python_etcd-0.3.2-py2.7.egg/etcd/__init.py", line 184, in handle
raise exc(msg, payload)
etcd.EtcdException: Unable to decode server response

**Comment by dreameryan** [comment]
BTW, when I run client.machines. It will output 
machines [u'http://localhost:2379', u'http://localhost:2379', u'http://localhost:4001', u'http://localhost:4001']
Seems it still find cluster machines from localhost.

**Comment by durzo** [comment]
This seems to be a cluster config issue. I have seen what you are experiencing before with a misconfigured cluster. Try re-creating the cluster being sure to specify the peer and client listen addresses as network reachable addresses (not localhost)

I have python-etcd from master branch working with etcd-v2.0.9 just fine:

durzo@test:~/etcd-v2.0.9-linux-amd64$ ./etcd
2015/04/08 22:22:41 etcd: no data-dir provided, using default data-dir ./default.etcd
2015/04/08 22:22:41 etcd: listening for peers on http://localhost:2380
2015/04/08 22:22:41 etcd: listening for peers on http://localhost:7001
2015/04/08 22:22:41 etcd: listening for client requests on http://localhost:2379
2015/04/08 22:22:41 etcd: listening for client requests on http://localhost:4001

durzo@test:~$ cat etcd-2.0.9.py 
#!/usr/bin/python
import etcd

client = etcd.Client(host='127.0.0.1', port=4001, protocol='http', allow_redirect=True, read_timeout=None)
print "Write: %s" % client.write('/test', "testing")
print "Read: %s" % client.read('/test').value

durzo@test:~$ ./etcd-2.0.9.py 
Write: <class 'etcd.EtcdResult'>({'newKey': True, 'raft_index': 76, '_children': [], 'createdIndex': 3, 'modifiedIndex': 3, 'value': u'testing', 'etcd_index': 3, 'expiration': None, 'key': u'/test', 'ttl': None, 'action': u'set', 'dir': False})
Read: testing

**Comment by dreameryan** [comment]
@durzo 
Hi, do you know how to config a etcd cluster?

I follow the etcd instruction ,and run following command on each machine, but it doesn't work:
/home/idcuser/HATest/etcd-v2.0.9-linux-amd64/etcd -name monitorserver1 -listen-peer-urls http://10.120.73.86:7001 -listen-client-urls http://10.120.73.86:4001 -initial-cluster-token monitorserver-cluster -initial-advertise-peer-urls http://10.120.73.86:7001 -initial-cluster monitorserver1=http://10.120.73.86:7001,monitorserve2=http://10.112.206.10:2380 -initial-cluster-state new &>> /home/idcuser/HATest/etcd.log &

/home/idcuser/HATest/etcd-v2.0.9-linux-amd64/etcd -name monitorserver2 -listen-peer-urls http://10.112.206.10:2380 -listen-client-urls http://10.112.206.10:2379 -initial-cluster-token monitorserver-cluster -initial-advertise-peer-urls http://10.112.206.10:2380 -initial-cluster monitorserver1=http://10.120.73.86:7001,monitorserver2=http://10.112.206.10:2380 -initial-cluster-state new &>> /home/idcuser/HATest/etcd.log &

**Comment by lavagetto** [comment]
seems like a config issue
