### ISSUE TITLE
client.update does not fail if value changed.

### ISSUE THREAD

**Issue by pheaver** [jplana/python-etcd#85]
This block of code will correctly fail if the /test node is modified by something else between reading and writing:
```
x = client.read('/test')
time.sleep(5)
client.write('/test', int(x.value) + 1, prevIndex = x.modifiedIndex)
```

But this code succeeds, and overwrites the value that was set elsewhere:
```
x = client.read('/test')
time.sleep(5)
x.value = int(x.value) + 1
client.update(x)
```

**Comment by durzo** [comment]
I can reproduce this error by using client.write (and also raw curl) - if you provide both prevExist=True and prevIndex then etcd ignores the prevIndex.

This is a bug in etcd and i have filed an issue here: https://github.com/coreos/etcd/issues/2684

As a workaround, use client.write and specify prevIndex without prevExist and the update will be atomic

**Comment by durzo** [comment]
this has now been fixed in etcd, please close this issue
