### ISSUE TITLE
cluster's localhost IP must be 'localhost'

### ISSUE THREAD

**Issue by stand1921** [jplana/python-etcd#91]
If you want to connect a cluster etcd,
you need to write the localhost's IP like 'localhost' as follow:

client = etcd.Client(
    host=(
        ('localhost', 4001),            //localhost IP
        ('192.168.1.33', 4001),     //other machine'IP of the cluster
    allow_reconnect=True,
)

you can‘t write the localhost's IP like '127.0.0.1' as follow, or the python-etcd will raise a exception:

client = etcd.Client(
    host=(
        ('127.0.0.1', 4001),
        ('192.168.1.33', 4001),
    allow_reconnect=True,
)

the problem is in python-etcd/client.py line 586:
      self._machine_cache = self.machines
because the self.machines function return 'localhost' instead of '127.0.0.1' if any machine of the cluster is on your host

Any idea to solve the problem? I can write some code to fix it if anyone have a good idea.
Or at least mention that in the doc

**Comment by lavagetto** [comment]
I think my PR from yesterday fixes this

https://github.com/jplana/python-etcd/pull/90

**Comment by stand1921** [comment]
OK
