### ISSUE TITLE
/v2/leader doesn't work in newer etcd versions

### ISSUE THREAD

**Issue by lavagetto** [jplana/python-etcd#93]
In versions of etcd >= 2.x, /v2/leader is not a valid endpoint anymore.

should we maintain backwards compatibility or should we just drop it?

**Comment by lechat** [comment]
I guess that whole point of having "v2" in etcd url is to avoid such incompatible changes...

Best approach would be to query ``http://127.0.0.1:4001/version`` before doing leader calls and raise exception if that version no longer supports leader endpoint.

**Comment by lavagetto** [comment]
@lechat "/v2/leader" worked just fine in 0.4.x, it has been removed since then.

As per your approach, I don't see a reason to fetch the info there at the moment, I'd probably just yank the code away.

**Comment by sukrit007** [comment]
API `http://localhost:4001/v2/stats/leader` might be another option to get leader hostname.

**Comment by lavagetto** [comment]
@sukrit007 thanks, I figured that out, but the solution I found is still incomplete. I don't think we can't live without this being 100% functional, so my current patch is ok and I should've closed this a long time ago.
